# Generated by Django 4.1 on 2022-08-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_note_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
