# Generated by Django 4.1 on 2022-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notebook_note_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
